name: typeson
description: Typed JSON values and a pluggable registry for custom (de)serialization with pretty building and custom parsers.
version: 1.0.0
repository: https://github.com/sunarya-thito/tson
homepage: https://github.com/sunarya-thito/tson

environment:
  sdk: ">=3.0.0 <4.0.0"

topics:
- json
- serialization
- encoding
- registry

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
